name: woven
version: 0.0.2
dependencies:
  angular: 0.12.0
  angular_node_bind: any
  shadow_dom: any
  browser: any
  polymer: ">=0.11.0 <0.12.0"
  core_elements: ">=0.0.6 <0.1.0"
  paper_elements: any
  firebase: ">=0.1.0 <0.2.0"
  meta: ">=0.8.8 <0.9.0"
  http_server: any
  google_oauth2_client: any
  google_plus_v1_api: any
  uri: ">=0.9.3 <0.10.0"
  query_string: any
transformers:
- angular:
    html_files:
    - web/index.html
- polymer:
    entry_points:
    - web/index.html
dependency_overrides:
  polymer: ">= 0.11.1-dev < 0.12.0"
  browser: any
  web_components: 0.4.0
  analyzer: ">=0.15.6 <0.16.0"
  html5lib: ">=0.11.0 <0.12.0"