name: woven
version: 0.0.2
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  polymer: ">=0.16.0 <0.17.0"
  core_elements: "^0.7.1+5"
  paper_elements: "^0.7.1+2"
  firebase: ">=0.6.3 <0.7.0"
  meta: ">=0.8.8 <0.9.0"
  http: any
  uri: ">=0.9.3 <0.10.0"
  query_string: any
  route: any
  crypto: ">=0.9.0 <0.10.0"
  intl: any
  logging: "^0.11.2"
  mustache: ">=0.1.8 <0.2.0"
  path: ">=1.3.0 <2.0.0"
  googleapis: ">=0.1.0 <0.2.0"
  googleapis_auth: ">=0.1.0 <0.3.0"
  jwt: ">=0.1.4 <0.2.0"
  notification: ">=0.0.1 <0.1.0"
  emoji: ">=1.0.3 <2.0.0"
  shelf: "^0.6.4+3"
  shelf_cors: "^0.2.1"
  shelf_static: "^0.2.3+1"
  html: "^0.12.2"
  xml: "^2.4.0"
  image: "^1.1.25"
dependency_overrides:
  core_elements:
    git: https://github.com/woven/core-elements
#  firebase:
#    git: https://github.com/davenotik/firebase-dart.git
transformers:
- polymer:
    entry_points:
    - web/index.html