name: woven
version: 0.0.2
dependencies:
  browser: any
  polymer: ">=0.15.0 <0.16.0"
  core_elements: ">=0.3.0+1 <0.4.0"
  paper_elements: ">=0.4.0 <0.5.0"
  firebase: ">=0.2.0+1 <0.3.0"
  meta: ">=0.8.8 <0.9.0"
  http_server: any
  http: any
  uri: ">=0.9.3 <0.10.0"
  query_string: any
  route: any
  crypto: ">=0.9.0 <0.10.0"
  intl: any
  mustache: ">=0.1.8 <0.2.0"
  mandrill_api: '>=1.0.0 <2.0.0'
transformers:
- polymer:
    entry_points:
    - web/index.html